"use client";

import { useState } from "react";

export default function ResultPreview({
  image,
  recommendedSize,
  fitNotes,
  styleNotes,
  confidence,
  loading,
}) {
  const [showPreview, setShowPreview] = useState(false);

  const handleOpen = () => {
    if (image) setShowPreview(true);
  };
  const handleClose = () => setShowPreview(false);

  return (
    <div className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm">
      <div className="flex items-center justify-between">
        <div>
          <p className="font-semibold text-gray-900">Try-On Result</p>
          <p className="text-sm text-gray-600">
            Generated by Gemini based on your photo and the product.
          </p>
        </div>
        {confidence !== null && confidence !== undefined ? (
          <div className="rounded-full bg-gray-100 px-3 py-1 text-xs font-medium text-gray-700">
            Confidence: {Math.round(confidence)}%
          </div>
        ) : null}
      </div>

      <div className="mt-4 grid gap-4 md:grid-cols-2">
        <div className="rounded-lg border border-dashed border-gray-200 bg-gray-50 p-3">
          {loading ? (
            <div className="flex h-64 items-center justify-center text-sm text-gray-500">
              Generating preview…
            </div>
          ) : image ? (
            <button
              type="button"
              onClick={handleOpen}
              className="group relative flex min-h-[16rem] w-full items-center justify-center focus:outline-none"
            >
              <img
                src={image}
                alt="Try-on preview"
                className="max-h-[22rem] w-full rounded-lg object-contain transition group-hover:opacity-90"
              />
              <span className="absolute right-3 top-3 rounded-full bg-black/70 px-3 py-1 text-xs font-medium text-white opacity-0 transition group-hover:opacity-100">
                View larger
              </span>
            </button>
          ) : (
            <div className="flex h-64 items-center justify-center text-sm text-gray-500">
              No preview yet
            </div>
          )}
        </div>

        <div className="flex flex-col gap-3">
          <div className="rounded-lg border border-gray-200 bg-gray-50 p-3">
            <p className="text-xs uppercase tracking-wide text-gray-500">
              Recommended Size
            </p>
            <p className="text-lg font-semibold text-gray-900">
              {recommendedSize || "—"}
            </p>
          </div>
          <div className="rounded-lg border border-gray-200 bg-gray-50 p-3">
            <p className="text-xs uppercase tracking-wide text-gray-500">
              Fit Notes
            </p>
            <p className="text-sm text-gray-800">
              {fitNotes || "No fit notes yet"}
            </p>
          </div>
          <div className="rounded-lg border border-gray-200 bg-gray-50 p-3">
            <p className="text-xs uppercase tracking-wide text-gray-500">
              Style Notes
            </p>
            <p className="text-sm text-gray-800">
              {styleNotes || "No style notes yet"}
            </p>
          </div>
        </div>
      </div>

      {showPreview ? (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 px-4"
          onClick={handleClose}
          role="dialog"
          aria-modal="true"
        >
          <div className="relative max-h-[90vh] max-w-5xl">
            <button
              type="button"
              onClick={handleClose}
              className="absolute right-2 top-2 rounded-full bg-white/90 px-3 py-1 text-xs font-semibold text-gray-900 shadow hover:bg-white"
            >
              Close
            </button>
            <img
              src={image}
              alt="Try-on preview enlarged"
              className="max-h-[90vh] w-full rounded-lg object-contain shadow-2xl"
              onClick={(e) => e.stopPropagation()}
            />
          </div>
        </div>
      ) : null}
    </div>
  );
}
