"use client";

export default function ResultPreview({
  image,
  recommendedSize,
  fitNotes,
  styleNotes,
  confidence,
  loading,
}) {
  return (
    <div className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm">
      <div className="flex items-center justify-between">
        <div>
          <p className="font-semibold text-gray-900">Try-On Result</p>
          <p className="text-sm text-gray-600">
            Generated by Gemini based on your photo and the product.
          </p>
        </div>
        {confidence !== null && confidence !== undefined ? (
          <div className="rounded-full bg-gray-100 px-3 py-1 text-xs font-medium text-gray-700">
            Confidence: {Math.round(confidence)}%
          </div>
        ) : null}
      </div>

      <div className="mt-4 grid gap-4 md:grid-cols-2">
        <div className="rounded-lg border border-dashed border-gray-200 bg-gray-50 p-3">
          {loading ? (
            <div className="flex h-64 items-center justify-center text-sm text-gray-500">
              Generating preview…
            </div>
          ) : image ? (
            <img
              src={image}
              alt="Try-on preview"
              className="h-64 w-full rounded-lg object-cover"
            />
          ) : (
            <div className="flex h-64 items-center justify-center text-sm text-gray-500">
              No preview yet
            </div>
          )}
        </div>

        <div className="flex flex-col gap-3">
          <div className="rounded-lg border border-gray-200 bg-gray-50 p-3">
            <p className="text-xs uppercase tracking-wide text-gray-500">
              Recommended Size
            </p>
            <p className="text-lg font-semibold text-gray-900">
              {recommendedSize || "—"}
            </p>
          </div>
          <div className="rounded-lg border border-gray-200 bg-gray-50 p-3">
            <p className="text-xs uppercase tracking-wide text-gray-500">
              Fit Notes
            </p>
            <p className="text-sm text-gray-800">
              {fitNotes || "No fit notes yet"}
            </p>
          </div>
          <div className="rounded-lg border border-gray-200 bg-gray-50 p-3">
            <p className="text-xs uppercase tracking-wide text-gray-500">
              Style Notes
            </p>
            <p className="text-sm text-gray-800">
              {styleNotes || "No style notes yet"}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
